use ineuron;
create table department (
id serial primary key,
name varchar(255) not null);

insert into department (name) values('Sales'),('marketing'),('IT');

SELECT * FROM DEPARTMENT;

create table employees (
ID SERIAL PRIMARY KEY,
NAME VARCHAR(255) NOT NULL,
DEPARTMENT_ID INT NOT NULL);

INSERT INTO EMPLOYEES (NAME,DEPARTMENT_ID) VALUES
('John Doe',1),('jane SMith',2),('Bob Jonhson',1),('Alice Lee',3);

## CREATE CTE THAT JOINS TWO TABLES AND SELECT THE NAME OF EMPLOYEE AND NAME OF THEIR DEPARTMENT
with employee_cte as(
select * from employees where department_id=1
)select * from employee_cte as e
join department as d on d.id = e.department_id;

##Example 4: Multiple SELECТ СТЕ

#Suppose we have a table named items that contains information about items in a store, 
#and a table named sales that contains information about sales made by the store. 
#We can create a CTE that selects the total number of items sold and the total revenue generated by 
#the store for each month.




CREATE TABLE items ( id SERIAL PRIMARY KEY, name VARCHAR(255) NOT NULL, price INTEGER NOT NULL );

CREATE TABLE sales (

id SERIAL PRIMARY KEY, item_id INTEGER NOT NULL, quantity INTEGER NOT NULL, sale_date DATE NOT NULL);

INSERT INTO items (name, price) VALUES
('Product A', 100),
('Product B', 200),
('Product C',300);

INSERT INTO sales (item_id, quantity, sale_date) VALUES
(1, 10, '2022-01-01') ,
(2,5,'2022-01-01'),
(3, 2, '2022-01-01') ,
(1, 20, '2022-02-01' ),
(2, 10, '2022-02-01' ),
(3, 4, '2022-02-01'),
(1, 30, '2022-03-01' ),
(2, 15, '2022-03-01' ),
(3, 6, '2022-03-01');



with monthly_sales as (
select 
month(s.sale_date) as sales_month ,
sum(s.quantity*i.price) as total_revenue  
from sales as s 
join items as i
on i.id = s.item_id
group by sales_month 
 
),
monthly_item_sold as (
select 
month(s.sale_date) as sales_month , 
sum(s.quantity) as item_sold 
from sales as s
group by sales_month
)select ms.sales_month,total_revenue , item_sold from monthly_sales as ms 
join monthly_item_sold as mis 
on ms.sales_month = mis.sales_month;




